packages:
  - 'packages/*'
  - 'packages/core/*'
  - 'packages/web/*'
  - 'packages/web/react/*'
  - 'packages/web/vue/*'
  - 'packages/web/svelte/*'
  - 'packages/mobile/*'
  - 'packages/mobile/react-native/*'
  - 'documentation/storybook*'
  - 'examples/*'
  - 'playground'
  - 'tools/*'